package main

var Icon_FileName = map[string]*iInfo{
	".pug-lintrc":                         iSet["pug"],
	".pug-lintrc.js":                      iSet["pug"],
	".pug-lintrc.json":                    iSet["pug"],
	".jscsrc":                             iSet["json"],
	".jshintrc":                           iSet["json"],
	"composer.lock":                       iSet["json"],
	".jsbeautifyrc":                       iSet["json"],
	".esformatter":                        iSet["json"],
	"cdp.pid":                             iSet["json"],
	".mjmlconfig":                         iSet["json"],
	".htaccess":                           iSet["xml"],
	".jshintignore":                       iSet["settings"],
	".buildignore":                        iSet["settings"],
	".mrconfig":                           iSet["settings"],
	".yardopts":                           iSet["settings"],
	"manifest.mf":                         iSet["settings"],
	".clang-format":                       iSet["settings"],
	".clang-tidy":                         iSet["settings"],
	"go.mod":                              iSet["go-mod"],
	"go.sum":                              iSet["go-mod"],
	"requirements.txt":                    iSet["python-misc"],
	"pipfile":                             iSet["python-misc"],
	".python-version":                     iSet["python-misc"],
	"manifest.in":                         iSet["python-misc"],
	"gradle.properties":                   iSet["gradle"],
	"gradlew":                             iSet["gradle"],
	"gradle-wrapper.properties":           iSet["gradle"],
	"license":                             iSet["certificate"],
	"license.md":                          iSet["certificate"],
	"license.txt":                         iSet["certificate"],
	"licence":                             iSet["certificate"],
	"licence.md":                          iSet["certificate"],
	"licence.txt":                         iSet["certificate"],
	"unlicense":                           iSet["certificate"],
	"unlicense.md":                        iSet["certificate"],
	"unlicense.txt":                       iSet["certificate"],
	".htpasswd":                           iSet["key"],
	"gemfile":                             iSet["gemfile"],
	"dockerfile":                          iSet["docker"],
	"dockerfile.prod":                     iSet["docker"],
	"dockerfile.production":               iSet["docker"],
	"docker-compose.yml":                  iSet["docker"],
	"docker-compose.yaml":                 iSet["docker"],
	"docker-compose.dev.yml":              iSet["docker"],
	"docker-compose.local.yml":            iSet["docker"],
	"docker-compose.ci.yml":               iSet["docker"],
	"docker-compose.override.yml":         iSet["docker"],
	"docker-compose.staging.yml":          iSet["docker"],
	"docker-compose.prod.yml":             iSet["docker"],
	"docker-compose.production.yml":       iSet["docker"],
	"docker-compose.test.yml":             iSet["docker"],
	".mailmap":                            iSet["email"],
	".graphqlconfig":                      iSet["graphql"],
	".gitignore":                          iSet["git"],
	".gitconfig":                          iSet["git"],
	".gitattributes":                      iSet["git"],
	".gitmodules":                         iSet["git"],
	".gitkeep":                            iSet["git"],
	"git-history":                         iSet["git"],
	".luacheckrc":                         iSet["lua"],
	".Rhistory":                           iSet["r"],
	"cmakelists.txt":                      iSet["cmake"],
	"cmakecache.txt":                      iSet["cmake"],
	"vue.config.js":                       iSet["vue-config"],
	"vue.config.ts":                       iSet["vue-config"],
	"nuxt.config.js":                      iSet["nuxt"],
	"nuxt.config.ts":                      iSet["nuxt"],
	"security.md":                         iSet["lock"],
	"security.txt":                        iSet["lock"],
	"security":                            iSet["lock"],
	"vercel.json":                         iSet["vercel"],
	".vercelignore":                       iSet["vercel"],
	"now.json":                            iSet["vercel"],
	".nowignore":                          iSet["vercel"],
	"postcss.config.js":                   iSet["postcss"],
	".postcssrc.js":                       iSet["postcss"],
	".postcssrc":                          iSet["postcss"],
	".postcssrc.json":                     iSet["postcss"],
	".postcssrc.yml":                      iSet["postcss"],
	"CNAME":                               iSet["http"],
	"webpack.js":                          iSet["webpack"],
	"webpack.ts":                          iSet["webpack"],
	"webpack.base.js":                     iSet["webpack"],
	"webpack.base.ts":                     iSet["webpack"],
	"webpack.config.js":                   iSet["webpack"],
	"webpack.config.ts":                   iSet["webpack"],
	"webpack.common.js":                   iSet["webpack"],
	"webpack.common.ts":                   iSet["webpack"],
	"webpack.config.common.js":            iSet["webpack"],
	"webpack.config.common.ts":            iSet["webpack"],
	"webpack.config.common.babel.js":      iSet["webpack"],
	"webpack.config.common.babel.ts":      iSet["webpack"],
	"webpack.dev.js":                      iSet["webpack"],
	"webpack.dev.ts":                      iSet["webpack"],
	"webpack.development.js":              iSet["webpack"],
	"webpack.development.ts":              iSet["webpack"],
	"webpack.config.dev.js":               iSet["webpack"],
	"webpack.config.dev.ts":               iSet["webpack"],
	"webpack.config.dev.babel.js":         iSet["webpack"],
	"webpack.config.dev.babel.ts":         iSet["webpack"],
	"webpack.prod.js":                     iSet["webpack"],
	"webpack.prod.ts":                     iSet["webpack"],
	"webpack.production.js":               iSet["webpack"],
	"webpack.production.ts":               iSet["webpack"],
	"webpack.server.js":                   iSet["webpack"],
	"webpack.server.ts":                   iSet["webpack"],
	"webpack.client.js":                   iSet["webpack"],
	"webpack.client.ts":                   iSet["webpack"],
	"webpack.config.server.js":            iSet["webpack"],
	"webpack.config.server.ts":            iSet["webpack"],
	"webpack.config.client.js":            iSet["webpack"],
	"webpack.config.client.ts":            iSet["webpack"],
	"webpack.config.production.babel.js":  iSet["webpack"],
	"webpack.config.production.babel.ts":  iSet["webpack"],
	"webpack.config.prod.babel.js":        iSet["webpack"],
	"webpack.config.prod.babel.ts":        iSet["webpack"],
	"webpack.config.prod.js":              iSet["webpack"],
	"webpack.config.prod.ts":              iSet["webpack"],
	"webpack.config.production.js":        iSet["webpack"],
	"webpack.config.production.ts":        iSet["webpack"],
	"webpack.config.staging.js":           iSet["webpack"],
	"webpack.config.staging.ts":           iSet["webpack"],
	"webpack.config.babel.js":             iSet["webpack"],
	"webpack.config.babel.ts":             iSet["webpack"],
	"webpack.config.base.babel.js":        iSet["webpack"],
	"webpack.config.base.babel.ts":        iSet["webpack"],
	"webpack.config.base.js":              iSet["webpack"],
	"webpack.config.base.ts":              iSet["webpack"],
	"webpack.config.staging.babel.js":     iSet["webpack"],
	"webpack.config.staging.babel.ts":     iSet["webpack"],
	"webpack.config.coffee":               iSet["webpack"],
	"webpack.config.test.js":              iSet["webpack"],
	"webpack.config.test.ts":              iSet["webpack"],
	"webpack.config.vendor.js":            iSet["webpack"],
	"webpack.config.vendor.ts":            iSet["webpack"],
	"webpack.config.vendor.production.js": iSet["webpack"],
	"webpack.config.vendor.production.ts": iSet["webpack"],
	"webpack.test.js":                     iSet["webpack"],
	"webpack.test.ts":                     iSet["webpack"],
	"webpack.dist.js":                     iSet["webpack"],
	"webpack.dist.ts":                     iSet["webpack"],
	"webpackfile.js":                      iSet["webpack"],
	"webpackfile.ts":                      iSet["webpack"],
	"ionic.config.json":                   iSet["ionic"],
	".io-config.json":                     iSet["ionic"],
	"gulpfile.js":                         iSet["gulp"],
	"gulpfile.mjs":                        iSet["gulp"],
	"gulpfile.ts":                         iSet["gulp"],
	"gulpfile.babel.js":                   iSet["gulp"],
	"package.json":                        iSet["nodejs"],
	"package-lock.json":                   iSet["nodejs"],
	".nvmrc":                              iSet["nodejs"],
	".esmrc":                              iSet["nodejs"],
	".node-version":                       iSet["nodejs"],
	".npmignore":                          iSet["npm"],
	".npmrc":                              iSet["npm"],
	".yarnrc":                             iSet["yarn"],
	"yarn.lock":                           iSet["yarn"],
	".yarnclean":                          iSet["yarn"],
	".yarn-integrity":                     iSet["yarn"],
	"yarn-error.log":                      iSet["yarn"],
	".yarnrc.yml":                         iSet["yarn"],
	".yarnrc.yaml":                        iSet["yarn"],
	"androidmanifest.xml":                 iSet["android"],
	".env.defaults":                       iSet["tune"],
	".env.example":                        iSet["tune"],
	".env.sample":                         iSet["tune"],
	".env.schema":                         iSet["tune"],
	".env.local":                          iSet["tune"],
	".env.dev":                            iSet["tune"],
	".env.development":                    iSet["tune"],
	".env.qa":                             iSet["tune"],
	".env.prod":                           iSet["tune"],
	".env.production":                     iSet["tune"],
	".env.staging":                        iSet["tune"],
	".env.preview":                        iSet["tune"],
	".env.test":                           iSet["tune"],
	".env.testing":                        iSet["tune"],
	".env.development.local":              iSet["tune"],
	".env.qa.local":                       iSet["tune"],
	".env.production.local":               iSet["tune"],
	".env.staging.local":                  iSet["tune"],
	".env.test.local":                     iSet["tune"],
	".babelrc":                            iSet["babel"],
	".babelrc.js":                         iSet["babel"],
	".babelrc.json":                       iSet["babel"],
	"babel.config.json":                   iSet["babel"],
	"babel.config.js":                     iSet["babel"],
	"contributing.md":                     iSet["contributing"],
	"readme.md":                           iSet["readme"],
	"readme.txt":                          iSet["readme"],
	"readme":                              iSet["readme"],
	"changelog":                           iSet["changelog"],
	"changelog.md":                        iSet["changelog"],
	"changelog.txt":                       iSet["changelog"],
	"changes":                             iSet["changelog"],
	"changes.md":                          iSet["changelog"],
	"changes.txt":                         iSet["changelog"],
	"credits":                             iSet["credits"],
	"credits.txt":                         iSet["credits"],
	"credits.md":                          iSet["credits"],
	"authors":                             iSet["authors"],
	"authors.md":                          iSet["authors"],
	"authors.txt":                         iSet["authors"],
	"favicon.ico":                         iSet["favicon"],
	"karma.conf.js":                       iSet["karma"],
	"karma.conf.ts":                       iSet["karma"],
	"karma.conf.coffee":                   iSet["karma"],
	"karma.config.js":                     iSet["karma"],
	"karma.config.ts":                     iSet["karma"],
	"karma-main.js":                       iSet["karma"],
	"karma-main.ts":                       iSet["karma"],
	".travis.yml":                         iSet["travis"],
	".codecov.yml":                        iSet["codecov"],
	"codecov.yml":                         iSet["codecov"],
	"protractor.conf.js":                  iSet["protractor"],
	"protractor.conf.ts":                  iSet["protractor"],
	"protractor.conf.coffee":              iSet["protractor"],
	"protractor.config.js":                iSet["protractor"],
	"protractor.config.ts":                iSet["protractor"],
	"procfile":                            iSet["heroku"],
	"procfile.windows":                    iSet["heroku"],
	".bowerrc":                            iSet["bower"],
	"bower.json":                          iSet["bower"],
	".eslintrc.js":                        iSet["eslint"],
	".eslintrc.cjs":                       iSet["eslint"],
	".eslintrc.yaml":                      iSet["eslint"],
	".eslintrc.yml":                       iSet["eslint"],
	".eslintrc.json":                      iSet["eslint"],
	".eslintrc":                           iSet["eslint"],
	".eslintignore":                       iSet["eslint"],
	".eslintcache":                        iSet["eslint"],
	"code_of_conduct.md":                  iSet["conduct"],
	"code_of_conduct.txt":                 iSet["conduct"],
	"mocha.opts":                          iSet["mocha"],
	".mocharc.yml":                        iSet["mocha"],
	".mocharc.yaml":                       iSet["mocha"],
	".mocharc.js":                         iSet["mocha"],
	".mocharc.json":                       iSet["mocha"],
	".mocharc.jsonc":                      iSet["mocha"],
	"jenkinsfile":                         iSet["jenkins"],
	"firebase.json":                       iSet["firebase"],
	".firebaserc":                         iSet["firebase"],
	"firestore.rules":                     iSet["firebase"],
	"firestore.indexes.json":              iSet["firebase"],
	".stylelintrc":                        iSet["stylelint"],
	"stylelint.config.js":                 iSet["stylelint"],
	".stylelintrc.json":                   iSet["stylelint"],
	".stylelintrc.yaml":                   iSet["stylelint"],
	".stylelintrc.yml":                    iSet["stylelint"],
	".stylelintrc.js":                     iSet["stylelint"],
	".stylelintignore":                    iSet["stylelint"],
	".codeclimate.yml":                    iSet["code-climate"],
	".prettierrc":                         iSet["prettier"],
	"prettier.config.js":                  iSet["prettier"],
	".prettierrc.js":                      iSet["prettier"],
	".prettierrc.json":                    iSet["prettier"],
	".prettierrc.yaml":                    iSet["prettier"],
	".prettierrc.yml":                     iSet["prettier"],
	".prettierignore":                     iSet["prettier"],
	"gruntfile.js":                        iSet["grunt"],
	"gruntfile.ts":                        iSet["grunt"],
	"gruntfile.coffee":                    iSet["grunt"],
	"gruntfile.babel.js":                  iSet["grunt"],
	"gruntfile.babel.ts":                  iSet["grunt"],
	"gruntfile.babel.coffee":              iSet["grunt"],
	"jest.config.js":                      iSet["jest"],
	"jest.config.ts":                      iSet["jest"],
	"jest.config.cjs":                     iSet["jest"],
	"jest.config.mjs":                     iSet["jest"],
	"jest.config.json":                    iSet["jest"],
	"jest.e2e.config.js":                  iSet["jest"],
	"jest.e2e.config.ts":                  iSet["jest"],
	"jest.e2e.config.cjs":                 iSet["jest"],
	"jest.e2e.config.mjs":                 iSet["jest"],
	"jest.e2e.config.json":                iSet["jest"],
	"jest.setup.js":                       iSet["jest"],
	"jest.setup.ts":                       iSet["jest"],
	"jest.json":                           iSet["jest"],
	".jestrc":                             iSet["jest"],
	".jestrc.js":                          iSet["jest"],
	".jestrc.json":                        iSet["jest"],
	"jest.teardown.js":                    iSet["jest"],
	"fastfile":                            iSet["fastlane"],
	"appfile":                             iSet["fastlane"],
	".helmignore":                         iSet["helm"],
	"makefile":                            iSet["makefile"],
	".releaserc":                          iSet["semantic-release"],
	".releaserc.yaml":                     iSet["semantic-release"],
	".releaserc.yml":                      iSet["semantic-release"],
	".releaserc.json":                     iSet["semantic-release"],
	".releaserc.js":                       iSet["semantic-release"],
	"release.config.js":                   iSet["semantic-release"],
	"bitbucket-pipelines.yaml":            iSet["bitbucket"],
	"bitbucket-pipelines.yml":             iSet["bitbucket"],
	"azure-pipelines.yml":                 iSet["azure-pipelines"],
	"azure-pipelines.yaml":                iSet["azure-pipelines"],
	"vagrantfile":                         iSet["vagrant"],
	"tailwind.js":                         iSet["tailwindcss"],
	"tailwind.config.js":                  iSet["tailwindcss"],
	"codeowners":                          iSet["codeowners"],
	".gcloudignore":                       iSet["gcp"],
	".huskyrc":                            iSet["husky"],
	"husky.config.js":                     iSet["husky"],
	".huskyrc.json":                       iSet["husky"],
	".huskyrc.js":                         iSet["husky"],
	".huskyrc.yaml":                       iSet["husky"],
	".huskyrc.yml":                        iSet["husky"],
	".commitlintrc":                       iSet["commitlint"],
	".commitlintrc.js":                    iSet["commitlint"],
	"commitlint.config.js":                iSet["commitlint"],
	".commitlintrc.json":                  iSet["commitlint"],
	".commitlint.yaml":                    iSet["commitlint"],
	".commitlint.yml":                     iSet["commitlint"],
	"dune":                                iSet["dune"],
	"dune-project":                        iSet["dune"],
	"roadmap.md":                          iSet["roadmap"],
	"roadmap.txt":                         iSet["roadmap"],
	"timeline.md":                         iSet["roadmap"],
	"timeline.txt":                        iSet["roadmap"],
	"milestones.md":                       iSet["roadmap"],
	"milestones.txt":                      iSet["roadmap"],
	"nuget.config":                        iSet["nuget"],
	".nuspec":                             iSet["nuget"],
	"nuget.exe":                           iSet["nuget"],
	"stryker.conf.js":                     iSet["stryker"],
	"stryker.conf.json":                   iSet["stryker"],
	".modernizrrc":                        iSet["modernizr"],
	".modernizrrc.js":                     iSet["modernizr"],
	".modernizrrc.json":                   iSet["modernizr"],
	// ".vfl":                                iSet["vfl"],
	// ".kl":                                 iSet["kl"],
	// "project.graphcool":                   iSet["graphcool"],
	// ".flowconfig":                         iSet["flow"],
	// ".bithoundrc":                         iSet["bithound"],
	// ".appveyor.yml":                       iSet["appveyor"],
	// "appveyor.yml":                        iSet["appveyor"],
	// "fuse.js":                             iSet["fusebox"],
	// ".editorconfig":                       iSet["editorconfig"],
	// ".watchmanconfig":                     iSet["watchman"],
	// "aurelia.json":                        iSet["aurelia"],
	// "rollup.config.js":                    iSet["rollup"],
	// "rollup.config.ts":                    iSet["rollup"],
	// "rollup-config.js":                    iSet["rollup"],
	// "rollup-config.ts":                    iSet["rollup"],
	// "rollup.config.common.js":             iSet["rollup"],
	// "rollup.config.common.ts":             iSet["rollup"],
	// "rollup.config.base.js":               iSet["rollup"],
	// "rollup.config.base.ts":               iSet["rollup"],
	// "rollup.config.prod.js":               iSet["rollup"],
	// "rollup.config.prod.ts":               iSet["rollup"],
	// "rollup.config.dev.js":                iSet["rollup"],
	// "rollup.config.dev.ts":                iSet["rollup"],
	// "rollup.config.prod.vendor.js":        iSet["rollup"],
	// "rollup.config.prod.vendor.ts":        iSet["rollup"],
	// ".hhconfig":                           iSet["hack"],
	// "apollo.config.js":                    iSet["apollo"],
	// "nodemon.json":                        iSet["nodemon"],
	// "nodemon-debug.json":                  iSet["nodemon"],
	// ".hintrc":                             iSet["webhint"],
	// "browserslist":                        iSet["browserlist"],
	// ".browserslistrc":                     iSet["browserlist"],
	// ".snyk":                               iSet["snyk"],
	// ".drone.yml":                          iSet["drone"],
	// ".sequelizerc":                        iSet["sequelize"],
	// "gatsby.config.js":                    iSet["gatsby"],
	// "gatsby-config.js":                    iSet["gatsby"],
	// "gatsby-node.js":                      iSet["gatsby"],
	// "gatsby-browser.js":                   iSet["gatsby"],
	// "gatsby-ssr.js":                       iSet["gatsby"],
	// ".wakatime-project":                   iSet["wakatime"],
	// "circle.yml":                          iSet["circleci"],
	// ".cfignore":                           iSet["cloudfoundry"],
	// "wallaby.js":                          iSet["wallaby"],
	// "wallaby.conf.js":                     iSet["wallaby"],
	// "stencil.config.js":                   iSet["stencil"],
	// "stencil.config.ts":                   iSet["stencil"],
	// ".bazelignore":                        iSet["bazel"],
	// ".bazelrc":                            iSet["bazel"],
	// "prisma.yml":                          iSet["prisma"],
	// ".nycrc":                              iSet["istanbul"],
	// ".nycrc.json":                         iSet["istanbul"],
	// "buildkite.yml":                       iSet["buildkite"],
	// "buildkite.yaml":                      iSet["buildkite"],
	// "netlify.json":                        iSet["netlify"],
	// "netlify.yml":                         iSet["netlify"],
	// "netlify.yaml":                        iSet["netlify"],
	// "netlify.toml":                        iSet["netlify"],
	// "nest-cli.json":                       iSet["nest"],
	// ".nest-cli.json":                      iSet["nest"],
	// "nestconfig.json":                     iSet["nest"],
	// ".nestconfig.json":                    iSet["nest"],
	// ".percy.yml":                          iSet["percy"],
	// ".gitpod.yml":                         iSet["gitpod"],
	// "tiltfile":                            iSet["tilt"],
	// "capacitor.config.json":               iSet["capacitor"],
	// ".adonisrc.json":                      iSet["adonis"],
	// "ace":                                 iSet["adonis"],
	// "meson.build":                         iSet["meson"],
	// ".buckconfig":                         iSet["buck"],
	// "nx.json":                             iSet["nrwl"],
	// ".slugignore":                         iSet["slug"],
}
